site_name: RACP

nav: 
  - Home: index.md
  - Example:
    - Example/crawl.md
  - Reference: 
    - Reference/crawl.md
    - Reference/utils.md

theme: readthedocs

plugins:
  - search
  - include-markdown
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src/racp]
